name: seychelles_sound
description: "A brand new Flutter project for Seychelles Sound."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.3.1
  encrypt: ^5.0.3
  http: ^1.6.0
  just_audio: ^0.10.6
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
